"""Add WorkCenter, Product models and enhance User, WorkOrder

Revision ID: 759ce93faab7
Revises: a8d12906febb
Create Date: 2025-09-20 18:05:00.807368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '759ce93faab7'
down_revision = 'a8d12906febb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('quantity_on_hand', sa.Integer(), nullable=True),
    sa.Column('reorder_level', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('department', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))

    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('work_center_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('assigned_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('paused_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('estimated_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('actual_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('issues', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('quality_check', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(None, 'work_centers', ['work_center_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['assigned_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('quality_check')
        batch_op.drop_column('issues')
        batch_op.drop_column('actual_cost')
        batch_op.drop_column('estimated_cost')
        batch_op.drop_column('paused_at')
        batch_op.drop_column('assigned_user_id')
        batch_op.drop_column('work_center_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_login')
        batch_op.drop_column('is_active')
        batch_op.drop_column('department')
        batch_op.drop_column('phone')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    op.drop_table('products')
    # ### end Alembic commands ###
