"""Add reorder_level column to components table

Revision ID: d7f23b4c8e91
Revises: c4d89e1bf2a3
Create Date: 2025-09-20 22:55:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7f23b4c8e91'
down_revision = 'c4d89e1bf2a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('components', sa.Column('reorder_level', sa.Integer(), nullable=True, default=10))
    # Set default value for existing records
    op.execute("UPDATE components SET reorder_level = 10 WHERE reorder_level IS NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('components', 'reorder_level')
    # ### end Alembic commands ###